### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by michaelpomogajko** [bridg-db/bridg#5]
Hi, 
although installed, it seems that the module is not being found when importing.

<img width="607" alt="Screenshot 2023-08-07 at 14 19 40" src="https://github.com/JoeRoddy/bridg/assets/8081364/4393eece-6b54-4a4b-920b-ef671c3306f2">

<img width="230" alt="Screenshot 2023-08-07 at 14 21 42" src="https://github.com/JoeRoddy/bridg/assets/8081364/59b01c7f-0c3c-423e-bcdd-47dc49e9a2ea">

<img width="1328" alt="Screenshot 2023-08-07 at 14 24 38" src="https://github.com/JoeRoddy/bridg/assets/8081364/47bd8795-e8b2-4a68-8a19-a0a0601e098a">

**Comment by JoeRoddy** [comment]
Hi @michaelpomogajko !

There's a janky generate command that you have to run to create your Bridg client along with your Prisma client (this will be replaced in time with a Prisma generator).  Not sure if you ran that, or if it failed maybe?

```json
{
  "scripts": {
    "generate": "npx prisma generate && npm explore bridg -- npm run generate"
  }
}
```

**Comment by michaelpomogajko** [comment]
I did ran it, it generated the test folder in the package as seen in the last image

**Comment by JoeRoddy** [comment]
Ah, I see, thanks.  Was there any error output from the generate command?  

By any chance are you on Windows?  There was an issue in the past with the generate command on Windows machines.  I thought I fixed it, but it's possible you might need to use WSL as a temporary fix.

If not, could you possibly give me some more info about your project, OS, etc?  

Did you clone one of the example apps, or setting it up on your own?  I see you're using Next, which is definitely the framework I've tested out the most.  But it's possible there's an issue with specific versions.

Any chance you could create an example repo that reproduces the issue?

Thanks so much opening this, will try to figure out whatever is causing it ASAP.

**Comment by michaelpomogajko** [comment]
Hi, yeah I'm receiving the following error when running the generate command

```
➜  bridg-test git:(main) ✗ yarn generate
yarn run v1.22.19
warning ../../package.json: No license field
$ npx prisma generate && npm explore bridg -- npm run generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
warn Preview feature "extendedWhereUnique" is deprecated. The functionality can be used without specifying it as a preview feature.

✔ Generated Prisma Client (5.1.1 | library) to ./node_modules/@prisma/client in 45ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

> bridg@1.0.30 generate
> npm run generate-ts && npm run build-client


> bridg@1.0.30 generate-ts
> node ./dist/generator/index.js ../../prisma/schema.prisma --outDir ./tmp


> bridg@1.0.30 build-client
> tsc ./tmp/**/*.ts --declaration --outDir ./ && mv client/* ./ && rm -rf ./tmp && rm -rf ./client

../@types/react-dom/node_modules/@types/react/index.d.ts:3244:14 - error TS2300: Duplicate identifier 'ElementType'.

3244         type ElementType = string | React.JSXElementConstructor<any>;
                  ~~~~~~~~~~~

  ../@types/react/index.d.ts:3244:14
    3244         type ElementType = string | React.JSXElementConstructor<any>;
                      ~~~~~~~~~~~
    'ElementType' was also declared here.

< --- shortened due to size --->

  ../@types/react/index.d.ts:3444:13
    3444             view: React.SVGProps<SVGViewElement>;
                     ~~~~
    'view' was also declared here.


Found 185 errors in 3 files.

Errors  Files
     3  ../@types/react-dom/node_modules/@types/react/index.d.ts:3244
     3  ../@types/react/index.d.ts:3244
   179  ../../../../node_modules/@types/react/index.d.ts:3234
npm ERR! code 2
npm ERR! path /Users/mpomogajko001/Desktop/bridg-test/node_modules/bridg
npm ERR! command failed
npm ERR! command sh -c npm run generate

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mpomogajko001/.npm/_logs/2023-08-08T09_39_26_556Z-debug-0.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  bridg-test git:(main) ✗

```

Here's the example repo
https://github.com/michaelpomogajko/bridg-example

I'm on a M1 Mac
Node v16

**Comment by michaelpomogajko** [comment]
Downgraded to prisma 4 and still receive an error when running the custom generate
This time it's: 

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

I'n on a MacBook M1 with 64GB RAM

**Comment by michaelpomogajko** [comment]
I did try it with the latest @4.x.x version of prisma. 

No rush, I'm just trying it out since I'm really excited about the approach the library takes. Actually thought of something like this myself couples months ago, but didn't have the skills to actually do it 😄

Happy that I can help with testing

**Comment by JoeRoddy** [comment]
Yeah I think the issue started happening in a higher version of 4, and still exists in Prisma 5.  The latest 4.x would def have the issue too.  I'm not sure of the exact version of Prisma where that heap error started happening though.

Try out `4.10.1` when you get a chance and lmk if that fixes it for you!

100% appreciate your help 🙌

**Comment by JoeRoddy** [comment]
@michaelpomogajko If you get a chance at some point, I just dropped a big rewrite.  Bridg now uses a prisma generator to create the client, instead of that janky `generate` script.  Prisma 5+ is now supported as well. (dropping support on earlier versions going forward, just so I can focus my efforts)

Installing:
```shell
npm i bridg@1.1.0
npm i prisma@5.1.1
npm i -D @prisma/client@5.1.1
```

`schema.prisma`:
```ts
generator client {
  provider = "prisma-client-js"
}

// Add this UNDER your prisma client
generator bridg {
  provider = "bridg"
}
```

`npx prisma generate`

**Comment by michaelpomogajko** [comment]
hi @JoeRoddy, tested it and it works out of the box. Thanks! 
I'll play around it some more and see If I can hack the caching we talked about

**Comment by JoeRoddy** [comment]
If anyone else runs into this issue, make sure you update Bridg and Prisma, instructions here: https://github.com/JoeRoddy/bridg/issues/5#issuecomment-1676488123

Thanks again for opening this Michael!

**Comment by bherbruck** [comment]
I'm still having issues with this on the demo `bridg-example-nextjs` demo:

```shell
npm run generate

> next-testing@0.1.0 generate
> prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator "bridg" failed:
```

```json
{
  "name": "next-testing",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "generate": "prisma generate",
    "push": "npx prisma db push"
  },
  "dependencies": {
    "@next/font": "13.1.4",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "bridg": "1.1.0",
    "eslint": "8.32.0",
    "eslint-config-next": "13.1.4",
    "next": "^13.5.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "@prisma/client": "5.1.1",
    "prisma": "5.1.1"
  }
}
```

**Comment by JoeRoddy** [comment]
thanks @bherbruck 

Is at the end of the output?  it just says: `Error: Generator "bridg" failed:`?

What operating system are you on?

**Comment by bherbruck** [comment]
> What operating system are you on?

I'm on debian on a devcontainer

**Comment by JoeRoddy** [comment]
thanks for the quick reply!  can I ask which package manager you're using (npm, yarn etc) and what version?  sorry, I forgot to ask in my original reply

**Comment by bherbruck** [comment]
I'm using npm
